name: Docker Build and Push to ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image to ECR
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Iniciar sesión en Amazon ECR
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # 3. Construir la imagen Docker
      - name: Build Docker image
        run: |
          docker build -t monitoring-app:latest .
          docker tag monitoring-app:latest 982081066879.dkr.ecr.us-east-1.amazonaws.com/monitoring-app:latest

      # 4. Subir la imagen a ECR
      - name: Push Docker image to ECR
        run: |
          docker push 982081066879.dkr.ecr.us-east-1.amazonaws.com/monitoring-app:latest
